[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["cd backend && npm install --omit=dev"]

[build]
cmds = ["echo 'Skipping build, backend only'"]

[start]
cmd = "cd backend && npm start"

